/** Sprint 113 R1/R2 — the allowlisted Insights output-language contract. */

export type InsightsLanguageSelection = 'auto' | 'et' | 'en';
export type InsightsOutputLanguage = Exclude<InsightsLanguageSelection, 'auto'>;

export interface InsightsLanguageMetadata {
  selected: InsightsLanguageSelection;
  resolved: InsightsOutputLanguage;
}

export const INSIGHTS_LANGUAGE_OPTIONS: ReadonlyArray<{
  value: InsightsLanguageSelection;
  label: string;
}> = [
  { value: 'auto', label: 'Auto' },
  { value: 'et', label: 'Estonian' },
  { value: 'en', label: 'English' },
];

const OUTPUT_LABELS: Record<InsightsOutputLanguage, string> = {
  et: 'Estonian',
  en: 'English',
};

export function isInsightsLanguageSelection(value: unknown): value is InsightsLanguageSelection {
  return value === 'auto' || value === 'et' || value === 'en';
}

export function resolveInsightsLanguage(
  selected: InsightsLanguageSelection,
  transcriptLanguage: string | null | undefined,
): InsightsOutputLanguage {
  if (selected !== 'auto') return selected;

  const detected = String(transcriptLanguage ?? '')
    .trim()
    .toLowerCase()
    .replace(/_/g, '-')
    .split('-')[0];
  return detected === 'et' ? 'et' : 'en';
}

export function insightsLanguageLabel(language: InsightsOutputLanguage): string {
  return OUTPUT_LABELS[language];
}

/** Old Insights were generated by an implicitly English prompt. */
export function insightsLanguageProvenance(
  language: InsightsLanguageMetadata | undefined,
): InsightsLanguageMetadata & { legacy: boolean } {
  return language
    ? { ...language, legacy: false }
    : { selected: 'en', resolved: 'en', legacy: true };
}
