/**
 * Sprint 108 R11 — session to markdown.
 *
 * Pure and vscode-free so it can be unit tested. Path resolution and the actual
 * write live in the export command (Phase 6).
 *
 * This is the artifact the user keeps. Because sessions live in hidden app
 * storage (D5), an export is written automatically when a transcription
 * completes — so this function's output, not the session file, is what survives
 * a reinstall.
 */

import * as path from 'path';
import type { TranscriptSession, TranscriptSegment } from './types';

/** `1:02:14` past an hour, `02:14` below it. */
export function formatTimestamp(seconds: number): string {
  const total = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const secs = total % 60;
  const pad = (value: number): string => String(value).padStart(2, '0');
  return hours > 0 ? `${hours}:${pad(minutes)}:${pad(secs)}` : `${pad(minutes)}:${pad(secs)}`;
}

/** `47 min`, `1 h 12 min` — for humans reading front matter. */
export function formatDuration(seconds: number): string {
  const total = Math.max(0, Math.round(seconds));
  const hours = Math.floor(total / 3600);
  const minutes = Math.round((total % 3600) / 60);
  if (hours > 0) return `${hours} h ${minutes} min`;
  if (minutes > 0) return `${minutes} min`;
  return `${total} s`;
}

/** Title from the recording's filename, tidied. */
export function titleFor(session: TranscriptSession): string {
  const base = path.basename(session.audioPath, path.extname(session.audioPath));
  const cleaned = base.replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim();
  if (!cleaned) return 'Transcript';
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

export function exportFileName(session: TranscriptSession): string {
  const base = path.basename(session.audioPath, path.extname(session.audioPath));
  const safe = base.replace(/[/\\:*?"<>|]/g, '-').trim() || 'transcript';
  return `${safe}.md`;
}

/** YAML-escape a scalar: quote it only when it could be misread. */
function yamlScalar(value: string): string {
  return /^[\w .,\-/()äöüõÄÖÜÕ]+$/.test(value) ? value : JSON.stringify(value);
}

function speakerLabel(session: TranscriptSession, segment: TranscriptSegment): string | null {
  if (!segment.speaker) return null;
  const speaker = session.speakers.find((candidate) => candidate.id === segment.speaker);
  return speaker?.label ?? segment.speaker;
}

function frontMatter(session: TranscriptSession): string {
  const lines: string[] = ['---'];
  lines.push(`title: ${yamlScalar(titleFor(session))}`);
  lines.push(`date: ${session.createdAt.slice(0, 10)}`);
  lines.push(`duration: ${yamlScalar(formatDuration(session.durationSec))}`);
  lines.push(`engine: ${yamlScalar(session.engine)}`);
  if (session.language) lines.push(`language: ${yamlScalar(session.language)}`);

  if (session.speakerSeparation === 'diarized' && session.speakers.length > 0) {
    lines.push(`speakers: [${session.speakers.map((speaker) => yamlScalar(speaker.label)).join(', ')}]`);
  } else {
    // Stated rather than omitted: a reader should know why the transcript has
    // no names, instead of assuming one person was talking (D3).
    lines.push('speakers: none — this engine cannot separate speakers');
  }

  lines.push(`source: ${yamlScalar(session.audioPath)}`);
  lines.push('---');
  return lines.join('\n');
}

function insightsSection(session: TranscriptSession): string[] {
  const insights = session.insights;
  if (!insights) return [];

  const lines: string[] = [];
  if (insights.summary) {
    lines.push('## Summary', '', insights.summary, '');
  }

  const groups: Array<{ kind: 'decision' | 'action' | 'question' | 'quote'; heading: string }> = [
    { kind: 'decision', heading: 'Decisions' },
    { kind: 'action', heading: 'Action items' },
    { kind: 'question', heading: 'Open questions' },
    { kind: 'quote', heading: 'Key quotes' },
  ];

  for (const group of groups) {
    const items = insights.items.filter((item) => item.kind === group.kind);
    if (items.length === 0) continue;

    lines.push(`## ${group.heading}`, '');
    for (const item of items) {
      const owner = item.owner ? `**${item.owner}** — ` : '';
      lines.push(`- ${owner}${item.text} \`${formatTimestamp(item.at)}\``);
    }
    lines.push('');
  }

  if (lines.length > 0) {
    lines.push(
      `_Summary, decisions and actions above were generated by ${insights.model} from the transcript below._`,
      '',
    );
  }

  return lines;
}

export function sessionToMarkdown(session: TranscriptSession): string {
  const lines: string[] = [frontMatter(session), '', `# ${titleFor(session)}`, ''];

  lines.push(...insightsSection(session));

  lines.push('## Transcript', '');

  let lastSpeaker: string | null = null;
  for (const segment of session.segments) {
    const label = speakerLabel(session, segment);
    const stamp = formatTimestamp(segment.start);

    if (label) {
      // Repeat the name only when the speaker changes; a name on every
      // paragraph of a monologue is noise.
      if (label !== lastSpeaker) {
        lines.push(`**${label}** · \`${stamp}\``, '');
        lastSpeaker = label;
      } else {
        lines.push(`\`${stamp}\``, '');
      }
    } else {
      lines.push(`\`${stamp}\``, '');
    }

    lines.push(segment.text, '');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}
