import { useState, type ReactNode } from 'react';
import { openExternalUrl } from '../../bridge';
import { Icon } from '../ui/Icon';
import {
  Dialog,
  DialogBody,
  DialogButton,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import {
  AI_INFORMATION_URL,
  RITEMARK_PRIVACY_URL,
  RITEMARK_TERMS_URL,
  acknowledgeFirstUseDisclosure,
  buildDisclosureContextRows,
  shouldShowFirstUseDisclosure,
  type AIIdentity,
  type DisclosureContextInput,
} from './aiDisclosure';

interface AIInformationDialogProps {
  identity: AIIdentity;
  context: DisclosureContextInput;
  open: boolean;
  showFirstUse: boolean;
  onOpenChange: (open: boolean) => void;
  onAcknowledge: () => void;
}

interface AIFirstUseDisclosureProps {
  identity: AIIdentity;
  onOpen: () => void;
  onDismiss: () => void;
}

interface ExternalLinkButtonProps {
  url: string;
  children: ReactNode;
}

function ExternalLinkButton({ url, children }: ExternalLinkButtonProps) {
  return (
    <button
      type="button"
      onClick={() => openExternalUrl(url)}
      className="inline-flex items-center gap-1 bg-transparent p-0 text-[11px] font-medium text-[var(--r-accent-deep)] hover:underline focus-visible:outline-none focus-visible:shadow-[0_0_0_2px_var(--r-ring-color)]"
    >
      {children}
      <Icon name="arrow-square-out" size={12} tone="active" />
    </button>
  );
}

export function useAIInformationDisclosure() {
  const [open, setOpen] = useState(false);
  const [showFirstUse, setShowFirstUse] = useState(() => shouldShowFirstUseDisclosure());

  const acknowledge = () => {
    acknowledgeFirstUseDisclosure();
    setShowFirstUse(false);
    setOpen(false);
  };

  return { open, setOpen, showFirstUse, acknowledge };
}

export function AIFirstUseDisclosure({ identity, onOpen, onDismiss }: AIFirstUseDisclosureProps) {
  return (
    <div
      className="mb-2 rounded-lg border border-[var(--r-hairline)] bg-[var(--r-accent-soft)] px-2.5 py-2 text-[var(--r-ink-body)]"
      role="status"
      aria-label="AI disclosure"
    >
      <div className="flex items-start gap-2">
        <Icon name="info" size={14} tone="active" className="mt-0.5 shrink-0" />
        <div className="min-w-0 flex-1">
          <div className="text-[11px] font-semibold text-[var(--r-ink-strong)]">
            You are interacting with AI
          </div>
          <div className="mt-0.5 text-[10px] leading-snug text-[var(--r-ink-muted)]">
            {identity.runtimeLabel} · {identity.providerLabel} · {identity.modelLabel}. AI can be wrong—review its output and changes.
          </div>
          <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1">
            <button
              type="button"
              onClick={onOpen}
              className="bg-transparent p-0 text-[10px] font-semibold text-[var(--r-accent-deep)] hover:underline focus-visible:outline-none focus-visible:shadow-[0_0_0_2px_var(--r-ring-color)]"
            >
              What may be shared?
            </button>
            <button
              type="button"
              onClick={onDismiss}
              className="inline-flex items-center gap-1 bg-transparent p-0 text-[10px] font-medium text-[var(--r-ink-muted)] hover:text-[var(--r-ink-strong)] hover:underline focus-visible:outline-none focus-visible:shadow-[0_0_0_2px_var(--r-ring-color)]"
            >
              <Icon name="check-square" size={12} />
              Don’t show again
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export function AIInformationButton({ onOpen }: { onOpen: () => void }) {
  return (
    <button
      type="button"
      onClick={onOpen}
      className="flex h-7 w-7 shrink-0 items-center justify-center rounded text-[var(--r-ink-muted)] hover:bg-[var(--r-surface-soft)] hover:text-[var(--r-ink-strong)] focus-visible:outline-none focus-visible:shadow-[0_0_0_2px_var(--r-ring-color)]"
      title="AI information"
      aria-label="AI information"
    >
      <Icon name="info" size={14} />
    </button>
  );
}

export function AIInformationDialog({
  identity,
  context,
  open,
  showFirstUse,
  onOpenChange,
  onAcknowledge,
}: AIInformationDialogProps) {
  const contextRows = buildDisclosureContextRows(context);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[calc(100%_-_32px)] max-w-[500px]">
          <DialogHeader icon={<Icon name="shield-check" size={20} tone="active" />} onClose={() => onOpenChange(false)}>
            <DialogTitle>AI information</DialogTitle>
          </DialogHeader>

          <DialogBody className="space-y-4">
            <DialogDescription className="leading-relaxed">
              Ritemark connects you to an external AI runtime. The response is generated by AI and can be inaccurate or incomplete.
            </DialogDescription>

            <section aria-labelledby="ai-current-selection">
              <h3 id="ai-current-selection" className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-[var(--r-ink-muted)]">
                Current selection
              </h3>
              <dl className="overflow-hidden rounded-lg border border-[var(--r-hairline)] bg-[var(--r-surface-muted)]/50 text-[12px]">
                {[
                  ['Runtime', identity.runtimeLabel],
                  ['Provider / service', identity.providerLabel],
                  ['Model', identity.modelLabel],
                ].map(([label, value]) => (
                  <div key={label} className="grid grid-cols-[7.5rem_1fr] gap-3 border-b border-[var(--r-hairline)] px-3 py-2 last:border-b-0">
                    <dt className="text-[var(--r-ink-muted)]">{label}</dt>
                    <dd className="min-w-0 break-words font-medium text-[var(--r-ink-strong)]">{value}</dd>
                  </div>
                ))}
              </dl>
            </section>

            <section aria-labelledby="ai-shared-context">
              <h3 id="ai-shared-context" className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-[var(--r-ink-muted)]">
                Context that may leave your device
              </h3>
              <div className="space-y-1.5">
                {contextRows.map((row) => (
                  <div key={row.id} className="flex gap-2 rounded-md border border-[var(--r-hairline)] bg-[var(--r-surface)] px-3 py-2">
                    <Icon
                      name={row.activeNow ? 'check-circle' : 'circle'}
                      size={14}
                      tone={row.activeNow ? 'active' : 'muted'}
                      className="mt-0.5 shrink-0"
                    />
                    <div className="min-w-0">
                      <div className="text-[11px] font-semibold text-[var(--r-ink-strong)]">
                        {row.label}{row.activeNow ? ' · present now' : ''}
                      </div>
                      <div className="mt-0.5 text-[10px] leading-relaxed text-[var(--r-ink-muted)]">{row.detail}</div>
                    </div>
                  </div>
                ))}
              </div>
              <p className="mt-2 text-[10px] leading-relaxed text-[var(--r-ink-muted)]">
                Your files stay on your computer as files, but their content can be sent when the selected runtime needs it. Depending on your permissions, an agent can also read other workspace files or use tools while completing a task.
              </p>
            </section>

            <section className="rounded-lg border border-[var(--r-hairline)] bg-[var(--r-surface-soft)] p-3" aria-labelledby="ai-review-output">
              <h3 id="ai-review-output" className="flex items-center gap-1.5 text-[11px] font-semibold text-[var(--r-ink-strong)]">
                <Icon name="warning-circle" size={14} />
                Review before relying on AI output
              </h3>
              <p className="mt-1 text-[10px] leading-relaxed text-[var(--r-ink-muted)]">
                Check factual claims, citations, calculations, commands, and file changes before you rely on, publish, or act on them. Approval controls reduce unintended actions; they do not make the output correct.
              </p>
            </section>

            <section aria-labelledby="ai-data-path">
              <h3 id="ai-data-path" className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-[var(--r-ink-muted)]">
                Data path and analytics
              </h3>
              <p className="text-[10px] leading-relaxed text-[var(--r-ink-muted)]">
                The selected runtime uses the account or API key configured for it and connects directly to its provider; Productory does not proxy AI requests. Separately, when Ritemark analytics is enabled, the app sends anonymous product-usage events to PostHog. Those events do not include prompt or file contents. Written feedback text is sent only when you explicitly submit it.
              </p>
            </section>

            <div className="flex flex-wrap gap-x-3 gap-y-1.5 border-t border-[var(--r-hairline)] pt-3">
              <ExternalLinkButton url={AI_INFORMATION_URL}>Ritemark AI information</ExternalLinkButton>
              <ExternalLinkButton url={RITEMARK_PRIVACY_URL}>Privacy policy</ExternalLinkButton>
              <ExternalLinkButton url={RITEMARK_TERMS_URL}>Terms of use</ExternalLinkButton>
              <ExternalLinkButton url={identity.providerInformationUrl}>{identity.providerLabel} information</ExternalLinkButton>
            </div>
          </DialogBody>

          <DialogFooter>
            <DialogButton onClick={showFirstUse ? onAcknowledge : () => onOpenChange(false)}>
              {showFirstUse ? 'I understand' : 'Done'}
            </DialogButton>
          </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
